# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

Ano = int(input("Digite um Ano: "))

if Ano % 4 == 0:
    print("O Ano {} é Bissexto".format(Ano))
else:
    print("O Ano {} não é Bissexto".format(Ano))
 
print("fim!")